micronaut:
  application:
    name: psp

jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: none
        show_sql: true
    entity-scan:
      packages: 'com.seyritey.psp.domain'