server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://psp-loki:3100/loki/api/v1/push

scrape_configs:

  - job_name: app
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/psp.log
    pipeline_stages:

      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag

      - regex:
          expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
          source: "tag"

      - labels:
          tag:
          stream:
          image_name:
          container_name:
          image_id:
          container_id:
  - job_name: clickhouseReplicatorLog
    static_configs:
      - targets:
          - localhost
        labels:
          job: clickhouseReplicatorLog
          __path__: /var/clickhouseReplicatorLog/clickhouseReplicator.log
    pipeline_stages:

      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag

      - regex:
          expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
          source: "tag"

      - labels:
          tag:
          stream:
          image_name:
          container_name:
          image_id:
          container_id: